[DRAFT] apply new, more generic analysis format
CERT-Polska/karton-config-extractor pull request #10
Opened 2021-04-08 09:05 UTC by kscieslinski

Karton instances should be data-driven and so should not require any additional knowledge about from whom the task originated.
I've marked this or. as draft as I have tested it only locally:
![poc](https://user-images.githubusercontent.com/26001306/113999447-58400000-985a-11eb-9633-3f67632e8368.png)

2021-04-08 10:57 UTC, psrok1 approved these changes
Nice, I like that unification. Looks ok, but we need to adapt some services before merge :+1:

2021-05-11 17:58 UTC, msm-code commented
I believe this is a breaking change, so you should probably increment a major version number. This also warrants a new release I think.

Correct me if I'm wrong.

2021-05-12 11:26 UTC, psrok1 commented on karton/config_extractor/config_extractor.py
> +                    dump_base = int(dump_metadata["base_address"], 16)
`int(..., 16)` should deal with both `03` and `0x03` forms

https://docs.python.org/3/library/functions.html#int

2021-05-12 14:10 UTC, kscieslinski commented on karton/config_extractor/config_extractor.py
> +                    dump_base = int(dump_metadata["base_address"], 16)
> Getting paranoid with JS int precision?
Yes

2021-05-12 14:14 UTC, kscieslinski commented
> I believe this is a breaking change, so you should probably increment a major version number. This also warrants a new release I think.
> 
> Correct me if I'm wrong.

updated version to 2.0.0

2021-05-12 14:17 UTC, kscieslinski commented on README.md
> +For the analysis type, the extractor tries to retrieve config from each memory dump passed in `dumps.zip` resource, but will pick only the best candidate from each family.
I've added some `analysis` task format description to README. Let me know if it's ok, or should I extend it.

2021-05-12 18:21 UTC, msm-code approved these changes
Approval because don't want to drag it out for longer (but we still need to update our internal code I think)

2021-05-12 18:21 UTC, msm-code commented on karton/config_extractor/config_extractor.py
> +                    dump_base = int(dump_metadata["base_address"], 16)
`int(..., 16) should deal with both 03 and 0x03 forms` I know, but it should be documented if that a part of the public API. Otherwise harmless refactoring may break some code.

2021-05-12 18:21 UTC, msm-code commented on README.md
> +where `dumps_metadata` contains information about filename and base address for every memory dump in `dumps.zip`.
I'd add something like

`baseaddr` is a string with a hex-encoded base address of the dump (leading `0x` is supported)

2021-05-12 18:44 UTC, psrok1 commented on README.md
> +where `dumps_metadata` contains information about filename and base address for every memory dump in `dumps.zip`.
```suggestion
where `dumps_metadata` contains information about every memory dump in `dumps.zip`. The following attributes are:
- `filename` which is relative path to the dumps.zip;
- `base_address` which hex-encoded base address for dump (leading `0x` is supported)

You can specify multiple entries for the same file if the same memory dump was found on different base addresses.
```

2021-05-12 18:48 UTC, psrok1 requested changes
Almost OK, but this documentation must be fixed a bit.

2021-05-12 18:48 UTC, psrok1 commented on README.md
> +            [...]],
It's `base_address` not `base_addr`
```suggestion
            {"filename": <dump1_filename>, "base_address": <dump1_baseaddr>},
            {"filename": <dump2_filename>, "base_address": <dump2_baseaddr>},
            {"filename": <dump3_filename>, "base_address": <dump3_baseaddr>},
            [...]],
```

In addition, there's no `resources` attribute in `Task()` (not included in suggestion). All keys are resources. It would be nice to see here more real-life example that uses `Resource.from_directory`.

If you need more hints, you can check our internal PR with Cuckoo integration (that code will be probably OSSed soon as well)

2021-05-12 18:51 UTC, msm-code commented on README.md
> +where `dumps_metadata` contains information about filename and base address for every memory dump in `dumps.zip`.
`relative path to the dumps.zip` relative is a key word kere :D. Actually, what if I put `/etc/passwd` there?

2021-05-12 19:57 UTC, psrok1 commented on README.md
> +where `dumps_metadata` contains information about filename and base address for every memory dump in `dumps.zip`.
Oh :see_no_evil: That should be spotted during https://github.com/CERT-Polska/karton-config-extractor/commit/ab6ad4ef6e773e094ef8f78e183f8e8fbe4dd2ea review.

2021-05-13 07:05 UTC, kscieslinski commented on README.md
> +            [...]],
Good catch:)

2021-05-13 08:05 UTC, kscieslinski commented on README.md
> +where `dumps_metadata` contains information about filename and base address for every memory dump in `dumps.zip`.
Done, applied @psrok1 suggestion.

2021-05-13 11:07 UTC, psrok1 commented on README.md
> +    payloads={
```suggestion
    payload={
```

2021-05-13 11:08 UTC, psrok1 approved these changes
Perfect :+1: Thanks @msm-code for in-depth look into documentation.

2021-05-13 11:19 UTC, merged